import { Inter } from "next/font/google";
import "./globals.css";
import GlobalNav from "@/components/my-ui/GlobalNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Practice Next Auth",
  description: "Generated by create next auth",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="min-h-screen flex flex-col absolute w-full">{children}
          <GlobalNav />
        </main>
      </body>
    </html>
  );
}
